name: gollum docker scheduled ci
on:
  schedule:
    - cron: '40 09 * * *'
    - cron: '40 10 * * *'
    - cron: '40 11 * * *'

env:
  DOCKERHUB_USERNAME: elcfd
  VERSION: 5.3.0

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [5.3.0, 5.3.0-869292ed-custom]
    steps:
      - name: install taskfile
        uses: arduino/setup-task@v1
      - name: source code checkout
        uses: actions/checkout@v2
      - name: run shellcheck
        uses: ludeeus/action-shellcheck@master
      - name: build
        run: task VERSION="${{matrix.version}}" build
      - name: check
        run: task VERSION="${{matrix.version}}" check
