name: gollum docker ci
on:
  push:

env:
  DOCKERHUB_USERNAME: elcfd

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [5.3.0, 5.3.0-869292ed-custom]
    steps:
      - name: install taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: source code checkout
        uses: actions/checkout@v2
      - name: run shellcheck
        uses: ludeeus/action-shellcheck@master
      - name: build
        run: task VERSION="${{matrix.version}}" build
      - name: check
        run: task VERSION="${{matrix.version}}" check
      - name: release
        if: contains(github.ref, 'release')
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          task VERSION="${{matrix.version}}" release
