name: gollum docker ci
on:
  push:
  schedule:
    - cron: '0 21 * * *'

env:
  DOCKERHUB_USERNAME: elcfd
  VERSION: 5.1.2

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: install taskfile
        run: |
          pushd /tmp && \
          wget https://github.com/go-task/task/releases/download/v3.0.0/task_linux_amd64.deb && \
          wget https://github.com/go-task/task/releases/download/v3.0.0/task_checksums.txt && \
          sha256sum -c --ignore-missing task_checksums.txt && \
          sudo dpkg -i task_linux_amd64.deb && \
          popd
      - name: source code checkout
        uses: actions/checkout@v2
      - name: build
        run: task VERSION="$VERSION" build
      - name: check
        run: task VERSION="$VERSION" check
