name: gollum docker ci
on:
  push:

env:
  DOCKERHUB_USERNAME: elcfd
  VERSION: 5.3.0

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: install taskfile
        uses: arduino/setup-task@v1
      - name: source code checkout
        uses: actions/checkout@v2
      - name: run shellcheck
        uses: ludeeus/action-shellcheck@master
      - name: build
        run: task VERSION="$VERSION" build
      - name: check
        run: task VERSION="$VERSION" check
      - name: release
        if: contains(github.ref, 'release')
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          task VERSION="$VERSION" release
