name: gollum docker ci
on:
  push:
  schedule:
    - cron: '0 21 * * *'

env:
  DOCKERHUB_USERNAME: elcfd
  VERSION: 5.2.3

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: install taskfile
        uses: Arduino/actions/setup-taskfile@master
      - name: source code checkout
        uses: actions/checkout@v2
      - name: build
        run: task VERSION="$VERSION" build
      - name: check
        run: task VERSION="$VERSION" check
      - name: release
        if: contains(github.ref, 'release')
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          task VERSION="$VERSION" release
